apiVersion: apps/v1
kind: Deployment
metadata:
  name: elecserve-deployment
  labels:
    app: elecserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elecserve
  template:
    metadata:
      labels:
        app: elecserve
    spec:
      containers:
      - name: elecserve
        image: terrasque/elecserve:7
        ports:
        - containerPort: 80
        env:
        - name: DB_ENGINE
          value: django.db.backends.postgresql
        - name: DB_NAME
          value: postgres
        - name: DB_USER
          value: postgres
        - name: DB_HOST
          value: postgres
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: elecserve-config
              key: postgres-password

        #- name: DEBUG
        #  value: "True"
        #- name: SECRET
        #  value: "somethingRandom"