# Generated by Django 3.2.6 on 2021-08-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markerpack',
            name='title',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
    ]
