# Generated by Django 3.2.6 on 2021-08-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_markerpack_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='markerpack',
            name='pack_id',
            field=models.CharField(default='-', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markerpack',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='markers.category')),
            ],
        ),
    ]
