# Generated by Django 3.2.6 on 2021-08-28 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_auto_20210828_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='markerpack',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='markers.category'),
            preserve_default=False,
        ),
    ]
